# Generated by Django 5.0.6 on 2024-05-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.TextField(verbose_name='Category Description')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Category Image')),
            ],
        ),
    ]
